version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - user-service
      - company-service
      - video-service

  postgres:
    image: postgres:14
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"] 
    #   interval: 5s
    #   timeout: 5s
    #   retries: 5
    ports:
      - "5432:5432"
    restart: unless-stopped

  user-service:
    build: ./user-service
    image: user-service:v1.0
    depends_on:
      - postgres
    restart: unless-stopped

  company-service:
    build: ./company-service
    image: company-service:v1.0
    depends_on:
      - postgres
    restart: unless-stopped

  video-service:
    build: ./video-service
    image: video-service:v1.0
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data: 
