version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - auth-service
      - company-service
      - video-service

  postgres:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  auth-service:
    build: ./auth-service
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres:5432/app
      - SECRET_KEY=your_secret_key_here
      - ACCESS_TOKEN_EXPIRE_DAYS=7
      - REFRESH_TOKEN_EXPIRE_DAYS=28
    depends_on:
      - postgres

  company-service:
    build: ./company-service
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres:5432/app
      - AUTH_SERVICE_URL=http://auth-service:8000
    depends_on:
      - postgres
      - auth-service

  video-service:
    build: ./video-service
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres:5432/app
      - AUTH_SERVICE_URL=http://auth-service:8000
      - COMPANY_SERVICE_URL=http://company-service:8000
    depends_on:
      - postgres
      - auth-service
      - company-service

volumes:
  postgres_data: 